### ISSUE TITLE
running the first php artisan key:generate I get an error

### ISSUE THREAD

**Issue by tbobker123** [greenrobotllc/adnetwork#1]
PHP Warning:  require(/home/siteflipp//bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/siteflipp//bootstrap/autoload.php on line 17

There is no vendor directory?  Is this missing or something I've done wrong here?

**Comment by andytriboletti** [comment]
Could you try running:

`php composer.phar install --no-scripts
mkdir bootstrap/cache
php composer.phar install`

**Comment by andytriboletti** [comment]
Did this solve your problem?
