### ISSUE TITLE
Dashboard issue.

### ISSUE THREAD

**Issue by shames11** [greenrobotllc/adnetwork#8]
When I clone the setup, configure .env with adserver and login on http://adnetwork.example.com with admin@yourdomain.com/password I get below error

The DB is pointed to adserver DB.

Help appreciated !

 Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'adserver.clicks' doesn't exist (SQL: select sum(cost) total from clicks where advertiser_user_id = 1 and click_date =2019-10-10)
Previous exceptions
![Screenshot from 2019-10-10 14-52-34](https://user-images.githubusercontent.com/56388588/66556385-be689b80-eb6d-11e9-847f-f6b55f7748a9.png)

    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'adserver.clicks' doesn't exist (42S02)

**Comment by andytriboletti** [comment]
This is the adnetwork project. Are you trying to run the adserver or the adnetwork?

Have you run

php artisan migrate
php artisan db:seed
